# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0emessages.proto\"\x13\n\x02Go\x12\r\n\x05steps\x18\x01 \x01(\x05\"\x06\n\x04Stop\"\xce\x01\n\x0cLinearPolicy\x12\x0e\n\x06k_bias\x18\x01 \x01(\x02\x12\x0f\n\x07k_droll\x18\x02 \x01(\x02\x12\x0e\n\x06k_dyaw\x18\x03 \x01(\x02\x12\x11\n\tk_dAngleW\x18\x04 \x01(\x02\x12\x10\n\x08k_dpitch\x18\x05 \x01(\x02\x12\x12\n\nk_dAngleTT\x18\x06 \x01(\x02\x12\x11\n\tk_xOrigin\x18\x07 \x01(\x02\x12\x11\n\tk_yOrigin\x18\x08 \x01(\x02\x12\x0e\n\x06k_roll\x18\t \x01(\x02\x12\r\n\x05k_yaw\x18\n \x01(\x02\x12\x0f\n\x07k_pitch\x18\x0b \x01(\x02\"O\n\rSetController\x12\x1c\n\x05wheel\x18\x01 \x01(\x0b\x32\r.LinearPolicy\x12 \n\tturntable\x18\x02 \x01(\x0b\x32\r.LinearPolicy\"b\n\tPCMessage\x12\x11\n\x02go\x18\x01 \x01(\x0b\x32\x03.GoH\x00\x12\x15\n\x04stop\x18\x02 \x01(\x0b\x32\x05.StopH\x00\x12$\n\ncontroller\x18\x03 \x01(\x0b\x32\x0e.SetControllerH\x00\x42\x05\n\x03msg\"\xb0\x02\n\x08LogEntry\x12\r\n\x05\x64roll\x18\x01 \x01(\x02\x12\x0c\n\x04\x64yaw\x18\x02 \x01(\x02\x12\x0f\n\x07\x64\x41ngleW\x18\x03 \x01(\x02\x12\x0e\n\x06\x64pitch\x18\x04 \x01(\x02\x12\x10\n\x08\x64\x41ngleTT\x18\x05 \x01(\x02\x12\x0f\n\x07xOrigin\x18\x06 \x01(\x02\x12\x0f\n\x07yOrigin\x18\x07 \x01(\x02\x12\x0c\n\x04roll\x18\x08 \x01(\x02\x12\x0b\n\x03yaw\x18\t \x01(\x02\x12\r\n\x05pitch\x18\n \x01(\x02\x12\t\n\x01x\x18\x0f \x01(\x02\x12\t\n\x01y\x18\x10 \x01(\x02\x12\x0e\n\x06\x41ngleW\x18\x11 \x01(\x02\x12\x0f\n\x07\x41ngleTT\x18\x12 \x01(\x02\x12\x16\n\x0eTurntableInput\x18\x13 \x01(\x02\x12\x12\n\nWheelInput\x18\x14 \x01(\x02\x12\x0b\n\x03\x64\x64x\x18\x15 \x01(\x02\x12\x0b\n\x03\x64\x64y\x18\x16 \x01(\x02\x12\x0b\n\x03\x64\x64z\x18\x17 \x01(\x02\"(\n\nLogMessage\x12\x1a\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\t.LogEntry\"\x19\n\x0c\x44\x65\x62ugMessage\x12\t\n\x01s\x18\x01 \x01(\t\"Q\n\x0cRobotMessage\x12\x1a\n\x03log\x18\x01 \x01(\x0b\x32\x0b.LogMessageH\x00\x12\x1e\n\x05\x64\x65\x62ug\x18\x02 \x01(\x0b\x32\r.DebugMessageH\x00\x42\x05\n\x03msgb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GO = _descriptor.Descriptor(
  name='Go',
  full_name='Go',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steps', full_name='Go.steps', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=37,
)


_STOP = _descriptor.Descriptor(
  name='Stop',
  full_name='Stop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=45,
)


_LINEARPOLICY = _descriptor.Descriptor(
  name='LinearPolicy',
  full_name='LinearPolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='k_bias', full_name='LinearPolicy.k_bias', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k_droll', full_name='LinearPolicy.k_droll', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k_dyaw', full_name='LinearPolicy.k_dyaw', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k_dAngleW', full_name='LinearPolicy.k_dAngleW', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k_dpitch', full_name='LinearPolicy.k_dpitch', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k_dAngleTT', full_name='LinearPolicy.k_dAngleTT', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k_xOrigin', full_name='LinearPolicy.k_xOrigin', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k_yOrigin', full_name='LinearPolicy.k_yOrigin', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k_roll', full_name='LinearPolicy.k_roll', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k_yaw', full_name='LinearPolicy.k_yaw', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='k_pitch', full_name='LinearPolicy.k_pitch', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=254,
)


_SETCONTROLLER = _descriptor.Descriptor(
  name='SetController',
  full_name='SetController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wheel', full_name='SetController.wheel', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='turntable', full_name='SetController.turntable', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=335,
)


_PCMESSAGE = _descriptor.Descriptor(
  name='PCMessage',
  full_name='PCMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='go', full_name='PCMessage.go', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop', full_name='PCMessage.stop', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='controller', full_name='PCMessage.controller', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='PCMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=337,
  serialized_end=435,
)


_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='droll', full_name='LogEntry.droll', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dyaw', full_name='LogEntry.dyaw', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dAngleW', full_name='LogEntry.dAngleW', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dpitch', full_name='LogEntry.dpitch', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dAngleTT', full_name='LogEntry.dAngleTT', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xOrigin', full_name='LogEntry.xOrigin', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yOrigin', full_name='LogEntry.yOrigin', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roll', full_name='LogEntry.roll', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='LogEntry.yaw', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='LogEntry.pitch', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='LogEntry.x', index=10,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='LogEntry.y', index=11,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AngleW', full_name='LogEntry.AngleW', index=12,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AngleTT', full_name='LogEntry.AngleTT', index=13,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TurntableInput', full_name='LogEntry.TurntableInput', index=14,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WheelInput', full_name='LogEntry.WheelInput', index=15,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ddx', full_name='LogEntry.ddx', index=16,
      number=21, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ddy', full_name='LogEntry.ddy', index=17,
      number=22, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ddz', full_name='LogEntry.ddz', index=18,
      number=23, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=742,
)


_LOGMESSAGE = _descriptor.Descriptor(
  name='LogMessage',
  full_name='LogMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='LogMessage.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=744,
  serialized_end=784,
)


_DEBUGMESSAGE = _descriptor.Descriptor(
  name='DebugMessage',
  full_name='DebugMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='DebugMessage.s', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=786,
  serialized_end=811,
)


_ROBOTMESSAGE = _descriptor.Descriptor(
  name='RobotMessage',
  full_name='RobotMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log', full_name='RobotMessage.log', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='debug', full_name='RobotMessage.debug', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='RobotMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=813,
  serialized_end=894,
)

_SETCONTROLLER.fields_by_name['wheel'].message_type = _LINEARPOLICY
_SETCONTROLLER.fields_by_name['turntable'].message_type = _LINEARPOLICY
_PCMESSAGE.fields_by_name['go'].message_type = _GO
_PCMESSAGE.fields_by_name['stop'].message_type = _STOP
_PCMESSAGE.fields_by_name['controller'].message_type = _SETCONTROLLER
_PCMESSAGE.oneofs_by_name['msg'].fields.append(
  _PCMESSAGE.fields_by_name['go'])
_PCMESSAGE.fields_by_name['go'].containing_oneof = _PCMESSAGE.oneofs_by_name['msg']
_PCMESSAGE.oneofs_by_name['msg'].fields.append(
  _PCMESSAGE.fields_by_name['stop'])
_PCMESSAGE.fields_by_name['stop'].containing_oneof = _PCMESSAGE.oneofs_by_name['msg']
_PCMESSAGE.oneofs_by_name['msg'].fields.append(
  _PCMESSAGE.fields_by_name['controller'])
_PCMESSAGE.fields_by_name['controller'].containing_oneof = _PCMESSAGE.oneofs_by_name['msg']
_LOGMESSAGE.fields_by_name['entries'].message_type = _LOGENTRY
_ROBOTMESSAGE.fields_by_name['log'].message_type = _LOGMESSAGE
_ROBOTMESSAGE.fields_by_name['debug'].message_type = _DEBUGMESSAGE
_ROBOTMESSAGE.oneofs_by_name['msg'].fields.append(
  _ROBOTMESSAGE.fields_by_name['log'])
_ROBOTMESSAGE.fields_by_name['log'].containing_oneof = _ROBOTMESSAGE.oneofs_by_name['msg']
_ROBOTMESSAGE.oneofs_by_name['msg'].fields.append(
  _ROBOTMESSAGE.fields_by_name['debug'])
_ROBOTMESSAGE.fields_by_name['debug'].containing_oneof = _ROBOTMESSAGE.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['Go'] = _GO
DESCRIPTOR.message_types_by_name['Stop'] = _STOP
DESCRIPTOR.message_types_by_name['LinearPolicy'] = _LINEARPOLICY
DESCRIPTOR.message_types_by_name['SetController'] = _SETCONTROLLER
DESCRIPTOR.message_types_by_name['PCMessage'] = _PCMESSAGE
DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY
DESCRIPTOR.message_types_by_name['LogMessage'] = _LOGMESSAGE
DESCRIPTOR.message_types_by_name['DebugMessage'] = _DEBUGMESSAGE
DESCRIPTOR.message_types_by_name['RobotMessage'] = _ROBOTMESSAGE

Go = _reflection.GeneratedProtocolMessageType('Go', (_message.Message,), dict(
  DESCRIPTOR = _GO,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Go)
  ))
_sym_db.RegisterMessage(Go)

Stop = _reflection.GeneratedProtocolMessageType('Stop', (_message.Message,), dict(
  DESCRIPTOR = _STOP,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Stop)
  ))
_sym_db.RegisterMessage(Stop)

LinearPolicy = _reflection.GeneratedProtocolMessageType('LinearPolicy', (_message.Message,), dict(
  DESCRIPTOR = _LINEARPOLICY,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:LinearPolicy)
  ))
_sym_db.RegisterMessage(LinearPolicy)

SetController = _reflection.GeneratedProtocolMessageType('SetController', (_message.Message,), dict(
  DESCRIPTOR = _SETCONTROLLER,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:SetController)
  ))
_sym_db.RegisterMessage(SetController)

PCMessage = _reflection.GeneratedProtocolMessageType('PCMessage', (_message.Message,), dict(
  DESCRIPTOR = _PCMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:PCMessage)
  ))
_sym_db.RegisterMessage(PCMessage)

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), dict(
  DESCRIPTOR = _LOGENTRY,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:LogEntry)
  ))
_sym_db.RegisterMessage(LogEntry)

LogMessage = _reflection.GeneratedProtocolMessageType('LogMessage', (_message.Message,), dict(
  DESCRIPTOR = _LOGMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:LogMessage)
  ))
_sym_db.RegisterMessage(LogMessage)

DebugMessage = _reflection.GeneratedProtocolMessageType('DebugMessage', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:DebugMessage)
  ))
_sym_db.RegisterMessage(DebugMessage)

RobotMessage = _reflection.GeneratedProtocolMessageType('RobotMessage', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:RobotMessage)
  ))
_sym_db.RegisterMessage(RobotMessage)


# @@protoc_insertion_point(module_scope)
